apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: modem
      tlsSkipVerify: true
    secureJsonData:
      # IMPORTANT: Update this token to match your INFLUX_TOKEN in .env
      token: my-super-secret-token
    isDefault: true
    editable: true
